from __future__ import annotations

import asyncio
import base64
import json
import os
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx
from playwright.async_api import async_playwright

from .config import DfbnetConfig


class AuthError(RuntimeError):
    pass


@dataclass
class TokenBundle:
    access_token: str | None = None
    refresh_token: str | None = None
    expires_at_ms: int | None = None
    access_token_stored_at_ms: int | None = None

    @property
    def has_access_token(self) -> bool:
        return bool(self.access_token)

    def expires_in_seconds(self) -> int | None:
        if not self.expires_at_ms:
            return None
        return int((self.expires_at_ms - int(time.time() * 1000)) / 1000)

    def access_token_expired(self, skew_seconds: int = 30) -> bool:
        remaining = self.expires_in_seconds()
        if remaining is None:
            exp = jwt_claim(self.access_token or "", "exp")
            if exp is None:
                return False
            return int(exp) <= int(time.time()) + skew_seconds
        return remaining <= skew_seconds


def jwt_claim(token: str, key: str) -> Any | None:
    try:
        parts = token.split(".")
        if len(parts) != 3:
            return None
        payload = parts[1] + "=" * (-len(parts[1]) % 4)
        return json.loads(base64.urlsafe_b64decode(payload.encode()).decode()).get(key)
    except Exception:
        return None


def summarize_token(token: str | None) -> dict[str, Any]:
    if not token:
        return {"present": False}
    out: dict[str, Any] = {"present": True, "length": len(token), "prefix": token[:10], "suffix": token[-10:]}
    for k in ["iss", "azp", "sub", "scope", "dfbnet_id", "dfbnet_techuser_id", "email", "iat", "exp"]:
        v = jwt_claim(token, k)
        if v is not None:
            out[k] = v
    if "exp" in out:
        out["expires_in_seconds"] = int(out["exp"]) - int(time.time())
    return out


def _bundle_from_mapping(data: dict[str, Any]) -> TokenBundle:
    return TokenBundle(
        access_token=data.get("access_token"),
        refresh_token=data.get("refresh_token"),
        expires_at_ms=int(data["expires_at"]) if data.get("expires_at") else None,
        access_token_stored_at_ms=int(data["access_token_stored_at"]) if data.get("access_token_stored_at") else None,
    )


def load_tokens_from_token_state(path: Path) -> TokenBundle:
    if not path.exists():
        raise AuthError(f"token_state not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    return _bundle_from_mapping(data)


def save_tokens_to_token_state(path: Path, tokens: dict[str, Any], existing_refresh_token: str | None = None) -> None:
    now_ms = int(time.time() * 1000)
    expires_in = int(tokens.get("expires_in", 300))
    data = {
        "access_token": tokens.get("access_token"),
        "refresh_token": tokens.get("refresh_token") or existing_refresh_token,
        "id_token": tokens.get("id_token"),
        "access_token_stored_at": str(now_ms),
        "expires_at": str(now_ms + expires_in * 1000),
        "updated_at": now_ms,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except Exception:
        pass


def _find_origin_state(storage_state: dict[str, Any], origin: str) -> dict[str, Any] | None:
    for item in storage_state.get("origins", []):
        if item.get("origin") == origin:
            return item
    return None


def _kv(storage_items: list[dict[str, Any]]) -> dict[str, str]:
    return {str(x.get("name")): str(x.get("value", "")) for x in storage_items}


def load_tokens_from_storage_state(path: Path, origin: str) -> TokenBundle:
    if not path.exists():
        raise AuthError(f"storage_state not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    origin_state = _find_origin_state(data, origin)
    if not origin_state:
        raise AuthError(f"No origin {origin!r} in storage_state: {path}. Playwright storage_state does not always include sessionStorage; use DFBNET_TOKEN_STATE generated by the updated probe script.")
    session = _kv(origin_state.get("sessionStorage", []))
    return _bundle_from_mapping(session)


def save_tokens_to_storage_state(path: Path, origin: str, tokens: dict[str, Any]) -> None:
    if not path.exists():
        return
    data = json.loads(path.read_text(encoding="utf-8"))
    origin_state = _find_origin_state(data, origin)
    if not origin_state:
        return
    ss = origin_state.setdefault("sessionStorage", [])
    existing = {x.get("name"): x for x in ss}

    now_ms = int(time.time() * 1000)
    expires_in = int(tokens.get("expires_in", 300))
    updates = {
        "access_token": tokens.get("access_token"),
        "refresh_token": tokens.get("refresh_token"),
        "id_token": tokens.get("id_token"),
        "access_token_stored_at": str(now_ms),
        "id_token_stored_at": str(now_ms),
        "expires_at": str(now_ms + expires_in * 1000),
        "id_token_expires_at": str(now_ms + expires_in * 1000),
    }
    for name, value in updates.items():
        if value is None:
            continue
        if name in existing:
            existing[name]["value"] = str(value)
        else:
            ss.append({"name": name, "value": str(value)})
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except Exception:
        pass


class TokenManager:
    def __init__(self, config: DfbnetConfig):
        self.config = config

    def load(self) -> TokenBundle:
        if self.config.token_state_path.exists():
            return load_tokens_from_token_state(self.config.token_state_path)
        return load_tokens_from_storage_state(self.config.storage_state_path, self.config.origin)

    async def auto_relogin(self) -> TokenBundle:
        """Attempt a headless Playwright auto-login when token refresh fails."""
        login_id = os.getenv("DFBNET_LOGIN_ID")
        password = os.getenv("DFBNET_PASSWORD")
        if not login_id or not password:
            raise AuthError(
                "Cannot auto-relogin: DFBNET_LOGIN_ID and DFBNET_PASSWORD not set. "
                "Ensure they are defined in ~/.dfbnet_env."
            )

        async def _do_relogin() -> bool:
            async with async_playwright() as pw:
                browser = await pw.chromium.launch(headless=True)
                try:
                    context = await browser.new_context(
                        viewport={"width": 1440, "height": 1000},
                        locale="de-DE",
                        timezone_id="Europe/Berlin",
                    )
                    page = await context.new_page()
                    await page.goto(self.config.origin, wait_until="domcontentloaded")

                    # Wait for redirect to Keycloak auth page
                    for _ in range(30):
                        if "auth.dfbnet.org" in page.url:
                            break
                        await page.wait_for_timeout(1000)

                    # Fill login form — try multiple selectors
                    async def _first_visible(selectors):
                        for sel in selectors:
                            try:
                                loc = page.locator(sel).first
                                if await loc.count() and await loc.is_visible(timeout=500):
                                    return sel
                            except Exception:
                                continue
                        return None

                    username_sel = await _first_visible([
                        "input#username", "input[name='username']",
                        "input[type='text']", "input[autocomplete='username']",
                    ])
                    password_sel = await _first_visible([
                        "input#password", "input[name='password']",
                        "input[type='password']", "input[autocomplete='current-password']",
                    ])

                    if not username_sel or not password_sel:
                        return False

                    await page.fill(username_sel, login_id)
                    await page.fill(password_sel, password)

                    submit_sel = await _first_visible([
                        "input#kc-login", "button#kc-login",
                        "input[type='submit']", "button[type='submit']",
                        "button:has-text('Anmelden')", "button:has-text('Einloggen')",
                    ])
                    if submit_sel:
                        await page.click(submit_sel)
                    else:
                        await page.keyboard.press("Enter")

                    # Wait for access_token in sessionStorage
                    for _ in range(60):
                        try:
                            tok_ok = await page.evaluate(
                                "() => !!sessionStorage.getItem('access_token')"
                            )
                        except Exception:
                            tok_ok = False
                        if tok_ok:
                            break
                        await page.wait_for_timeout(1000)

                    if not tok_ok:
                        return False

                    # Export token_state.json
                    token_state = await page.evaluate(
                        """() => {
                            const keys = ['access_token', 'refresh_token', 'id_token',
                                'access_token_stored_at', 'expires_at',
                                'id_token_expires_at', 'session_state'];
                            const out = { exported_at: Date.now(), origin: location.origin };
                            for (const key of keys) {
                                const val = sessionStorage.getItem(key);
                                if (val !== null) out[key] = val;
                            }
                            return out;
                        }"""
                    )
                    tpath = self.config.token_state_path
                    tpath.parent.mkdir(parents=True, exist_ok=True)
                    tpath.write_text(json.dumps(token_state, indent=2, ensure_ascii=False), encoding="utf-8")
                    os.chmod(tpath, 0o600)

                    # Export storage_state.json
                    spath = self.config.storage_state_path
                    spath.parent.mkdir(parents=True, exist_ok=True)
                    await context.storage_state(path=str(spath))
                    os.chmod(spath, 0o600)

                    return True
                finally:
                    await browser.close()

        ok = await _do_relogin()
        if not ok:
            raise AuthError(
                "Headless auto-relogin failed. Open https://sria.dfbnet.org in a normal browser, "
                "log in manually to refresh the session, then try again."
            )
        return self.load()

    async def refresh(self, refresh_token: str) -> TokenBundle:
        url = f"{self.config.auth_base_url}/protocol/openid-connect/token"
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                url,
                data={
                    "grant_type": "refresh_token",
                    "client_id": self.config.client_id,
                    "refresh_token": refresh_token,
                },
                headers={"content-type": "application/x-www-form-urlencoded"},
            )
        if resp.status_code >= 400:
            raise AuthError(f"Token refresh failed with HTTP {resp.status_code}: {resp.text[:300]}")
        payload = resp.json()
        save_tokens_to_token_state(self.config.token_state_path, payload, existing_refresh_token=refresh_token)
        save_tokens_to_storage_state(self.config.storage_state_path, self.config.origin, payload)
        return self.load()

    async def get_valid_access_token(self) -> str:
        bundle = self.load()
        if not bundle.access_token:
            raise AuthError("No access_token. Run the updated scripts/dfbnet_login_probe.py locally; set DFBNET_TOKEN_STATE to dfbnet_probe_out/token_state.json.")
        if bundle.access_token_expired(skew_seconds=45):
            if not bundle.refresh_token:
                raise AuthError("Access token expired and no refresh_token. Re-run interactive login probe.")
            try:
                bundle = await self.refresh(bundle.refresh_token)
            except AuthError:
                # Refresh token itself is dead — fall back to headless auto-relogin
                bundle = await self.auto_relogin()
        if not bundle.access_token:
            raise AuthError("Token refresh did not produce access_token")
        return bundle.access_token
